micronaut:
  application:
    name: mn2-liquibase-transaction
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
